//region annotations
/*:
 * @target MZ
 * @plugindesc [v1.0.0 CAMODS] JS Mods exclusive to Chef Adventure.
 * @author JE
 * @url https://github.com/je-can-code/rmmz-plugins
 * @help
 * ============================================================================
 * OVERVIEW
 * These modifications of code are modifications against various components of
 * the core scripts. Additionally, plugins I've written are also modified here
 * in a way that I consider "not-mainstream enough" to be published as a part
 * of the original plugins.
 *
 * NOTE ABOUT USING THIS "PLUGIN":
 * While I do list below the various changes that are provided by this plugin
 * modifier, I do not intend to support this as a public plugin, so you should
 * probably not use this plugin unless you want 100% of the functionality
 * listed below, or are able to tweak/adjust the code yourself.
 *
 * This is also NOT a versioned plugin, and can potentially change without
 * any notification.
 *
 * Use with caution!
 *
 * ============================================================================
 * SYSTEM CHANGES:
 * - additional equip slot for all actors (as accessory)
 * - "recover all" recovers TP too
 * - random variable assignment for "rare/named enemies" on map transfer
 *
 * ----------------------------------------------------------------------------
 * CA-UNIQUE CHANGES:
 * - inanimate enemies grant no rewards of any kind
 * - loot drop x,y adjustment unique to CA
 * - anti-null elementIds hard-coded
 * - target frame text autogenerated from the four CA "trait" elements
 * - helpers for locating the elemental allies by actor id
 * ============================================================================
 */
//endregion annotations

//#region src/plugins/__ca-mods/core/_metadata/_pluginMetadata.js
var J_CaModsPluginMetadata = class extends PluginMetadata {
	/**
	* Constructor.
	* @param {string} name The name driving this step.
	* @param {string} version The version driving this step.
	*/
	constructor(name, version) {
		super(name, version);
	}
};

//#endregion
//#region src/plugins/__ca-mods/core/_metadata/initialization.js
/**
* The core where all of my extensions live: in the `J` object.
*/
globalThis.J ||= {};
/**
* The plugin umbrella that governs all things related to this plugin.
*/
J.CAMods = {};
/**
* The metadata associated with this plugin, such as name and version.
*/
J.CAMods.Metadata = new J_CaModsPluginMetadata("J-CA-Mods", "1.0.0");
/**
* The actual `plugin parameters` extracted from RMMZ.
*/
J.CAMods.PluginParameters = J.CAMods.Metadata.parsedPluginParameters;
/**
* A collection of all aliased methods for this plugin.
*/
J.CAMods.Aliased = {};
J.CAMods.Aliased.JABS_Battler = new Map();
J.CAMods.Aliased.JABS_Engine = new Map();
J.CAMods.Aliased.Game_Actor = new Map();
J.CAMods.Aliased.Game_BattlerBase = new Map();
J.CAMods.Aliased.Game_Map = new Map();
J.CAMods.Aliased.Game_Party = new Map();
J.CAMods.Aliased.Scene_Boot = new Map();

//#endregion
//#region src/plugins/__ca-mods/core/_models/JABS_Battler.js
/**
* Extends {@link #getTargetFrameText}.<br/>
* If no text was provided for the target, instead autogenerate some text based on their traits.
* The "traits" are defined by arbitrary CA-specific elements, so this can't live in the
* target frame plugin, or the monsterpedia plugin.
* @returns {string}
*/
J.CAMods.Aliased.JABS_Battler.set("getTargetFrameText", JABS_Battler.prototype.getTargetFrameText);
JABS_Battler.prototype.getTargetFrameText = function() {
	const originalTargetFrameText = J.CAMods.Aliased.JABS_Battler.get("getTargetFrameText").call(this);
	if (originalTargetFrameText !== String.empty) return originalTargetFrameText;
	const battler = this.getBattler();
	const isArmed = battler.elementRate(21) > 1;
	const isFlying = battler.elementRate(22) > 1;
	const isShielded = battler.elementRate(23) > 1;
	const hasAura = battler.elementRate(24) > 1;
	const hasNoTraits = ![
		isArmed,
		isFlying,
		isShielded,
		hasAura
	].some((trait) => !!trait);
	if (hasNoTraits) return String.empty;
	const traits = [];
	if (isArmed) {
		traits.push("Weaponized");
	}
	if (isFlying) {
		traits.push("Flying");
	}
	if (isShielded) {
		traits.push("Shielded");
	}
	if (hasAura) {
		traits.push("Aural");
	}
	const text = traits.join(", ");
	return text;
};

//#endregion
//#region src/plugins/__ca-mods/core/objects/Game_Action.js
/**
* Implements {@link #getAntiNullElementIds}.<br/>
* In CA, these elementIds define tools, which should be considered regardless.
*/
Game_Action.prototype.getAntiNullElementIds = function() {
	return [
		25,
		26,
		27,
		28
	];
};

//#endregion
//#region src/plugins/__ca-mods/core/objects/Game_Actor.js
/**
* Extends {@link #equipSlots}.<br/>
* Adds a duplicate of the 5th type (accessory).
*/
J.CAMods.Aliased.Game_Actor.set("equipSlots", Game_Actor.prototype.equipSlots);
Game_Actor.prototype.equipSlots = function() {
	const baseSlots = J.CAMods.Aliased.Game_Actor.get("equipSlots").call(this);
	baseSlots.push(5);
	return baseSlots;
};
/**
* Refreshes all auto-equippable skills available to this battler.
*/
Game_Actor.prototype.refreshAutoEquippedSkills = function() {
	const allSlots = this.getAllEquippedSkills();
	this.skills().forEach((skill) => {
		const skillId = skill.id;
		if (allSlots.some((slot) => slot.id === skillId)) return;
		this.jabsProcessLearnedSkill(skill.id);
	}, this);
};

//#endregion
//#region src/plugins/__ca-mods/core/objects/Game_BattlerBase.js
/**
* Extends {@link #recoverAll}.<br/>
* Using the event command for "Recover All" also restores all TP to the battler.
*/
J.CAMods.Aliased.Game_BattlerBase.set("recoverAll", Game_BattlerBase.prototype.recoverAll);
Game_BattlerBase.prototype.recoverAll = function() {
	J.CAMods.Aliased.Game_BattlerBase.get("recoverAll").call(this);
	this._tp = this.maxTp();
};

//#endregion
//#region src/plugins/__ca-mods/core/objects/Game_Map.js
/**
* Extends {@link #setup}.<br/>
* Upon map initialization, assigns a random integer between 1-100 to an arbitrary variable.
* In CA, this value is used to determine the presence of "rare/named" monsters on the map.
*/
J.CAMods.Aliased.Game_Map.set("setup", Game_Map.prototype.setup);
Game_Map.prototype.setup = function(mapId) {
	J.CAMods.Aliased.Game_Map.get("setup").call(this, mapId);
	$gameVariables.setValue(13, Math.randomInt(100) + 1);
};

//#endregion
//#region src/plugins/__ca-mods/core/objects/Game_Party.js
/**
* The actorIds that correlate with elemental actors in regards to Chef Adventure.
* @type {number[]}
*/
Game_Party.ELEMENTAL_ALLY_ACTOR_IDS = [
	3,
	4,
	5,
	6
];
/**
* Gets all current actors that are just the elemental variety.
* @returns {Game_Actor[]}
*/
Game_Party.prototype.elementalActors = function() {
	return $gameParty.battleMembers().filter((member) => Game_Party.ELEMENTAL_ALLY_ACTOR_IDS.contains(member.actorId()));
};
/**
* Gets all current JABS Battlers that are just the elemental variety.
* @returns {JABS_Battler[]}
*/
Game_Party.prototype.elementalJabsBattlers = function() {
	const filtering = (jabsBattler) => {
		const actorId = jabsBattler.getBattler().actorId();
		return Game_Party.ELEMENTAL_ALLY_ACTOR_IDS.includes(actorId);
	};
	return JABS_AiManager.getActorBattlers().filter(filtering, this);
};
/**
* Determine if the leader is the given actorId.
* @param {number} actorId The actor id to compare the leader's actor id with.
* @returns {boolean} True if the leader is the same actor as the designated id, false otherwise.
*/
Game_Party.prototype.isLeaderActor = function(actorId) {
	return this.leader().actorId() === actorId;
};

//#endregion
//#region src/plugins/__ca-mods/core/managers/JABS_Engine.js
/**
* Extends {@link #canGainReward}.<br/>
* Inanimate enemies (trees, shrubs, ore deposits, destructibles) do not grant any rewards in CA.
* Their levels are intentionally high to gate resource access — not to serve as experience farms.
* @param {Game_Enemy} defeatedEnemy The enemy that was defeated.
* @param {Game_Actor} victoriousActor The actor that defeated the enemy.
* @returns {boolean} False if the defeated enemy is inanimate, otherwise defers to the base check.
*/
J.CAMods.Aliased.JABS_Engine.set("canGainReward", JABS_Engine.prototype.canGainReward);
JABS_Engine.prototype.canGainReward = function(defeatedEnemy, victoriousActor) {
	if (defeatedEnemy.isInanimate() === true) {
		return false;
	}
	return J.CAMods.Aliased.JABS_Engine.get("canGainReward").call(this, defeatedEnemy, victoriousActor);
};
/**
* Fixes the weird problem where CA uniquely seems to want to move character sprites up
* by 1 when generating loot.
* @param {number} targetX The `x` coordiante where the loot will be dropped/placed.
* @param {number} targetY The `y` coordinate where the loot will be dropped/placed.
*/
J.CAMods.Aliased.JABS_Engine.set("addLootDropToMap", JABS_Engine.prototype.addLootDropToMap);
JABS_Engine.prototype.addLootDropToMap = function(targetX, targetY, item) {
	const modifiedTargetY = targetY + 1;
	return J.CAMods.Aliased.JABS_Engine.get("addLootDropToMap").call(this, targetX, modifiedTargetY, item);
};

//#endregion
//# sourceMappingURL=J-CA-Mods.js.map