//region Map_TextPop
/**
 * A class representing a single popup on the map.
 */
function Map_TextPop()
{
  this.initialize(...arguments);
}
Map_TextPop.prototype = {};
Map_TextPop.prototype.constructor = Map_TextPop;

/**
 * A static collection of all types associated with text pops.
 */
Map_TextPop.Types = {
  /**
   * The popup type of "hp-damage", for displaying hp damage pops.
   */
  HpDamage: 'hp-damage',

  /**
   * The popup type of "mp-damage", for displaying mp damage pops.
   */
  MpDamage: 'mp-damage',

  /**
   * The popup type of "tp-damage", for displaying tp damage pops.
   */
  TpDamage: 'tp-damage',

  /**
   * The popup type of "evade", for evasion pops.
   * Though, these aren't officially supported by JABS.
   */
  Evade: 'evade',

  /**
   * The popup type of "parry", for when a skill was used, but also parried.
   */
  Parry: 'parry',

  /**
   * The popup type of "experience", for displaying gained experience pops.
   */
  Experience: 'exp',

  /**
   * The popup type of "gold", for displaying earned gold pops.
   */
  Gold: 'gold',

  /**
   * The popup type of "levelup", for displaying levelups pops.
   */
  Levelup: 'levelup',

  /**
   * The popup type of "item", for displaying loot pops.
   */
  Item: 'item',

  /**
   * The popup type of "slip", for displaying pops generated by slip damage/healing.
   */
  Slip: 'slip',

  /**
   * The popup type of "skillLearn", for displaying skills learned as a pop.
   */
  Learn: 'skillLearn',

  /**
   * The popup type of "sdp", for displaying SDP points earned after defeating foes.
   */
  Sdp: 'sdp',

  /**
   * The popup type of "skillUsage", for displaying used skills as popups off the battlers on the map.
   */
  SkillUsage: 'skillUsage',
};

/**
 * Builds the text pop based on the given parameters.
 */
Map_TextPop.prototype.initialize = function({
  iconIndex,
  textColorIndex,
  popupType,
  value,
  critical,
  coordinateVariance,
  healing,
})
{
  /**
   * The id of the icon to display alongside this `Map_TextPop`.
   * @type {number}
   */
  this.iconIndex = iconIndex;

  /**
   * The color index for the text color.
   * @type {number}
   */
  this.textColorIndex = textColorIndex;

  /**
   * The type of popup this is, such as damage, experience, loot, etc.
   * @type {Map_TextPop.Types}
   */
  this.popupType = popupType;

  /**
   * The value to display on the sprite for this popup.
   * @type {string}
   */
  this.value = value || String.empty;

  /**
   * Whether or not this popup is critical.
   * For non-damage popups, this is always false.
   * @type {boolean}
   */
  this.critical = critical || false;

  /**
   * The x and y coordinate variances into a single `[x,y]` array.
   * @type {[number, number]}
   */
  this.coordinateVariance = coordinateVariance;

  /**
   * Whether or not this popup is healing.
   * Healing popups' motion is handled a bit differently.
   * @type {boolean}
   */
  this.healing = healing;
};
//endregion Map_TextPop